name: Update Repository Names

on:
  workflow_dispatch:
    inputs:
      csv-file:
        description: 'Path to the CSV file with repo names'
        required: true
        default: 'mapping.csv'

jobs:
  update-repos:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get install -y python3 python3-pip
          pip3 install pandas PyGithub

      - name: Run update script
        run: python3 update_repos.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
